version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-demo
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend-demo
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend-demo
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:
